openapi: 3.0.3
info:
  title: Swagger Fullstack - OpenAPI 3.0
  description: |-
    API Almacén
  version: 1.0.0
servers:
  - url: /
tags:
  - name: articulo
    description: Altículos del almacén
  - name: consumidor
    description: Consumidores de la aplicación
paths:
  /api/articulos:
    get:
      tags:
        - articulo
      summary: Busca articulos
      description: Busca todos los articulos y permite filtros por código y activo
      operationId: buscar_articulos
      parameters:
        - name: codigo
          in: query
          description: Código del articulo
          required: false
          schema:
            type: string
        - name: activo
          in: query
          description: Indicador de articulo activo
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articulo'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
    post:
      tags:
        - articulo
      summary: Crea un articulo
      description: Crea un articulo
      operationId: crear_articulo
      requestBody:
        description: Artículo a crear
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/articulo'
        required: true
      responses:
        '201':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articulo'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []

  /api/articulos/{codigo}:
    get:
      tags:
        - articulo
      summary: Busca un articulo
      description: Busca un articulo
      operationId: busca_articulo      
      parameters:
        - name: codigo
          in: path
          description: Código del articulo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articulo'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
    put:
      tags:
        - articulo
      summary: Actualiza un articulo
      description: Actualiza un articulo
      operationId: actualiza_articulo
      parameters:
        - name: codigo
          in: path
          description: Código del articulo
          required: true
          schema:
            type: string
      requestBody:
        description: Artículo a actualizar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/articulo'
        required: true
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articulo'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
    delete:
      tags:
        - articulo
      summary: Borra un articulo
      description: Borra articulo a partir del código
      operationId: borra_articulo
      parameters:
        - name: codigo
          in: path
          description: Código del articulo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/consumidores:
    post:
      tags:
        - consumidor
      summary: Crea un consumidor
      description: Crea un consumidor
      operationId: crear_consumiudor
      parameters:
        - name: consumidor
          in: query
          description: nombre del consumidor que deseamos crear
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumidor'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/articulos/recepcion:
    put:
      tags:
        - articulo
      summary: Entrada de artículos
      description: Registra la entrada de un artículo e incrementa el stock
      operationId: recepcionar_articulos
      parameters:
        - name: codigo
          in: query
          description: Código del articulo
          required: true
          schema:
            type: string
        - name: cantidad
          in: query
          description: Cantidad que entra del artículo
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articulo'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/articulos/salida:
    put:
      tags:
        - articulo
      summary: Salida de artículos
      description: Registra la salida de un artículo y decrementa su stock
      operationId: salida_articulos
      parameters:
        - name: codigo
          in: query
          description: Código del articulo
          required: true
          schema:
            type: string
        - name: cantidad
          in: query
          description: Cantidad que entra del artículo
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articulo'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY 
  schemas:
    articulo:
      type: object
      description: Artículo de almaceén
      properties:
        id:
          description: "Identificador interno"
          type: string
          example: "da3fc73f-b4a9-4533-92cb-b8dbd70a8f8a"
        codigo:
          description: "Codigo del artículo"
          type: string
          example: "BOLI"
        descripcion:
          description: "Descripción del artículo"
          type: string
          example: "Boligrafo"
        stock:
          description: "Stock en almacén"
          type: integer
          format: int32
          example: 4
        activo:
          description: "Indicador de activo"
          type: boolean
          example: True
    consumidor:
      type: object
      description: Consumidor
      properties:
        id:
          description: "Identificador interno"
          type: string
          example: da3fc73f-b4a9-4533-92cb-b8dbd70a8f8a
        codigo:
          description: "API-KEY del consumidor"
          type: string
          example: "da3f345-b4a9-4345-92hg-basef40a8f66"
        descripcion:
          description: "Nombre del consumidor"
          type: string
          example: "Consumidor tienda"
        activo:
          description: "Indicador de activo"
          type: boolean
          example: True
