openapi: 3.0.3
info:
  title: Swagger Fullstack - OpenAPI 3.0
  description: |-
    API Tienda
  version: 1.0.0
servers:
  - url: /
tags:
  - name: producto
    description: Producto de la tienda
  - name: consumidor
    description: Consumidores de la aplicación
paths:
  /api/productos:
    get:
      tags:
        - producto
      summary: Busca productos
      description: Busca todos los productos y permite filtros por código y activo
      operationId: buscar_productos
      parameters:
        - name: codigo
          in: query
          description: Código del producto
          required: false
          schema:
            type: string
        - name: activo
          in: query
          description: Indicador de producto activo
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
    post:
      tags:
        - producto
      summary: Crea un producto
      description: Crea un producto
      operationId: crear_producto
      requestBody:
        description: Producto a crear
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/producto'
        required: true
      responses:
        '201':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []

  /api/productos/{codigo}:
    get:
      tags:
        - producto
      summary: Busca un producto
      description: Busca un producto
      operationId: busca_producto      
      parameters:
        - name: codigo
          in: path
          description: Código del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
    put:
      tags:
        - producto
      summary: Actualiza un producto
      description: Actualiza un producto
      operationId: actualiza_producto
      parameters:
        - name: codigo
          in: path
          description: Código del producto
          required: true
          schema:
            type: string
      requestBody:
        description: Producto a actualizar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/producto'
        required: true
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
    delete:
      tags:
        - producto
      summary: Borra un producto
      description: Borra producto a partir del código
      operationId: borra_producto
      parameters:
        - name: codigo
          in: path
          description: Código del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/consumidores:
    post:
      tags:
        - consumidor
      summary: Crea un consumidor
      description: Crea un consumidor
      operationId: crear_consumiudor
      parameters:
        - name: consumidor
          in: query
          description: nombre del consumidor que deseamos crear
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/consumidor'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/productos/precio:  
    put:
      tags:
        - producto
      summary: Actualiza el precio de un producto
      description: permite actualizar el precio y activo de un producto
      operationId: actualzia_precio
      parameters:
        - name: codigo
          in: query
          description: Código del producto
          required: true
          schema:
            type: string
        - name: precio
          in: query
          description: Nuevo precio del producto
          required: true
          schema:
            type: number
            format: float
        - name: activo
          in: query
          description: Activo
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/productos/reponer:  
    put:
      tags:
        - producto
      summary: Reponer un producto 
      description: repone un producto conectándose al API almacén
      operationId: reponer_producto
      parameters:
        - name: codigo
          in: query
          description: Código del producto
          required: true
          schema:
            type: string
        - name: cantidad
          in: query
          description: Cantidad a reponer
          required: true
          schema:
            type: integer
            format: int32
        - name: adapta_a_disponibilidad
          in: query
          description: Si no hay suficiente stock, repongo el que pueda
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []
  /api/productos/vender:  
    put:
      tags:
        - producto
      summary: Reponer un producto 
      description: repone un producto conectándose al API almacén
      operationId: vender_producto
      parameters:
        - name: codigo
          in: query
          description: Código del producto
          required: true
          schema:
            type: string
        - name: cantidad
          in: query
          description: Cantidad a cender
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/producto'          
        '400':
          description: Entrada incorrecta
        '404':
          description: Recurso no encontrado
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY 
  schemas:
    producto:
      type: object
      description: Producto de tienda
      properties:
        id:
          description: "Identificador interno"
          type: string
          example: "da3fc73f-b4a9-4533-92cb-b8dbd70a8f8a"
        codigo:
          description: "Codigo del producto"
          type: string
          example: "BOLI"
        descripcion:
          description: "Descripción del producto"
          type: string
          example: "Boligrafo"
        precio:
          description: "Precio del producto"
          type: number
          format: float
          example: 3.4
        stock:
          description: "Stock en tienda"
          type: integer
          format: int32
          example: 4
        vendidos:
          description: "Unidades vendidas"
          type: integer
          format: int32
          example: 2
        activo:
          description: "Indicador de activo"
          type: boolean
          example: True
    consumidor:
      type: object
      description: Consumidor
      properties:
        id:
          description: "Identificador interno"
          type: string
          example: da3fc73f-b4a9-4533-92cb-b8dbd70a8f8a
        codigo:
          description: "API-KEY del consumidor"
          type: string
          example: "da3f345-b4a9-4345-92hg-basef40a8f66"
        descripcion:
          description: "Nombre del consumidor"
          type: string
          example: "Consumidor tienda"
        activo:
          description: "Indicador de activo"
          type: boolean
          example: True
