name: Pipeline Backend
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run:
            python -m pip install --upgrade pip
            pip install pylint pytest flask
      - name: Pylint
        run:  |
            find . -name "*.py" -type f -print0 | xargs -0 pylint
      - name: Pytest
        run: |
            find . -name "test_*.py" -type f -print0 | xargs -0 pytest
                
