name: Pipeline Backend
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
      - name: Install dependencies
        run:
            python -m pip install --upgrade pip
            pip install pylint pytest flask            
      - name: Concede permisos de ejecución a sh de instalación de dependencias
        run: 
            chmod +x install_requirements.sh
      - name: Run Install Script
        run: 
            ./install_requirements.sh            
      - name: Pylint
        run:  |
            find . -type f -name "*.py" -print0 | xargs -0 pylint
      - name: Pytest
        run: |
            find . -type f -name "test_*.py" -print0 | xargs -0 pytest
                
